version: 2.1

orbs:
  maven: circleci/maven@1.3.0

jobs:
  build:
    executor: maven/default
    working_directory: ~/sfg-pet-clinic
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
      - run:
          name: Test
          command: |
            mvn -s ./settings.xml clean test
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

workflows:
  main:
    jobs:
      - build